### ISSUE TITLE
예외 처리 및 Client Response 방법 통일

### ISSUE THREAD

**Issue by HaenaCho01** [JisooPyo/Trillion-NewSpeed-Project#10]
1. 제가 기존에 ResponseMessageDto로 사용하던 dto랑 행복님께서 작성하신 ApiResponseDto가 내용이 겹치는 것 같아서 
클래스명이 더 적절한 ApiResponseDto로 통일해보면 어떨까요?

2. ResponseEntity를 사용한 예외 처리 및 Response 방법이 행복님께서 사용하신 방법이 더 적절하게 판단이 되어서 행복님 방식으로 통일하면 어떨까싶은데 다른 분들 의견은 어떤지 듣고 싶습니다!

**Comment by JisooPyo** [comment]
다 같이 ApiResponseDto / ResponseEntity 로 통일하기로 결정!! 땅땅!!
