### ISSUE TITLE
겹치는 태그 처리

### ISSUE THREAD

**Issue by JisooPyo** [JisooPyo/Trillion-NewSpeed-Project#2]
POST1 - #상체운동
POST 2 - #상체운동
POST 3 - #상체운동

이런식으로 하나의 태그가 여러 개 겹치는데, 이 때, 겹치는 태그 처리 어떻게 할것인지!

**Comment by JisooPyo** [comment]
![겹치는 태그 처리 방법](https://github.com/JisooPyo/Trillion-NewSpeed-Project/assets/130378232/3a8cd497-64be-43c4-ad4d-279615d2de92)
이런 식으로 하면 될 거 같지만, 너무 복잡해 질 수 있으니, 일단은 겹쳐도 해 보는 방향으로 가고, 추후 시간에 여유가 있으면 이 방법으로 개선시켜 보는 것으로 한다.

**Comment by HaenaCho01** [comment]
넵 이후에 시간 여유 되면 개선 진행해보도록 하겠습니다!👍
