### ISSUE TITLE
댓글 좋아요 기능 중 좋아요 취소 등의 구현에 관한 논의

### ISSUE THREAD

**Issue by HaenaCho01** [JisooPyo/Trillion-NewSpeed-Project#3]
댓글 좋아요 기능을 현재 ERD 내에서 구현하려면 좋아요를 누른 user의 정보가 DB에 존재하지 않아 
좋아요 취소가 어렵고, 같은 사용자가 무한정으로 좋아요를 누를 수가 있습니다.

좋아요 기능이 필수가 아니라 옵션 기능이라 수정없이 이대로 좋아요 기능을 구현하고 
다른 기능 개발에 신경쓰는 게 좋을지 

아니면 해당 문제를 해결하기 위해 아래 블로그를 참고하여 ERD를 수정하여 코드를 작성하거나
혹은 다른 수정 방법은 없을지 의논이 필요할 듯 합니다.

해당 문제 해결에 도움이 될만한 레퍼런스 블로그를 첨부합니다. 참고 부탁드립니다!

[스프링부트 게시판 API 만들기 - 13 게시물 좋아요 기능 만들기]
https://hose.tistory.com/18

**Comment by JisooPyo** [comment]
블로그를 읽어보면 현재
수정할 파일 : CommentController, CommentService, CommentEntity, UserEntity,
생성할 파일 : CommentLikeEntity, CommentLikeRepository
이렇게 볼 수 있을까요?

댓글을 작성할 포스트와 user을 받아와서 like를 남기는 식으로..
일단은 ERD를 수정하여 다른 기능을 먼저 구현하고 필수 기능이 다 구현된다면 좋아요 기능을 구현해 보는거로 해봐도 좋을 것 같습니다!
그 부분을 구현을 못한다면 주석에라도 이런이런 로직으로 구현해 보려고 했다! 정도 남겨놔도 좋을 거 같아요!
일단 구현한다고 생각하고 ERD 수정하면 좋을 것 같습니다!

**Comment by HaenaCho01** [comment]
지수님이 말씀하신 내용이 맞아요! 네넵 바로 진행해보도록 하겠습니다!!👍
