### ISSUE TITLE
예외 처리 방식(해나님 issue)

### ISSUE THREAD

**Issue by JisooPyo** [JisooPyo/Trillion-NewSpeed-Project#5]
예외 처리를 dto 형식으로 만들어서 response에 반환하는 것이 맞는건가!

**Comment by JisooPyo** [comment]
튜터님께 조언을 구함 >> 프론트엔드와 협업을 할 때는 json 형식으로 줘야 그쪽에서도 메시지를 출력해줄 수 있기 때문에 그렇게 하는 것이 좋다!

**Comment by HaenaCho01** [comment]
앗 지수님이 더 빨랐다..

**Comment by JisooPyo** [comment]
아앗 해나님이 올려주시려고 했군요! 다음부터는 해나님께 맡길게요옹.. 헤헹

**Comment by HaenaCho01** [comment]
앗ㅋㅋㅋㅋ네넵 뭔가 지수님이 올리시고 지수님이 답변하시면 외로워보일까봐..(?) 다음엔 좀 더 빨리 올려보겠습니다!
